### ISSUE TITLE
Change output to use Tabulate

### ISSUE THREAD

**Issue by Dannyzen** [Dannyzen/lirr#2]
https://pypi.python.org/pypi/tabulate 
I'm thinking

source_name destination_name Duration
1:11 1:20 9
2:11 2:20 9
3:11 3:20 9
4:11 4:20 9

**Comment by jcrivera** [comment]
This is an example of how to do it, but I don't know how to smoothly integrate the tabulate library so users don't have to run pip install: https://github.com/groddeck/lirr/tree/tabulate
